- hosts: ai
  become: yes
  become_method: sudo
  tasks:
  - name: Copy requirements installation file
    synchronize:
      src: "{{ repo_dir }}/Ansible/"
      dest: "{{ home_dir }}/requirements/"
      delete: yes
      archive: yes
      compress: yes
      use_ssh_args: yes
      rsync_opts:
        - "--include=*requirements*"
        - "--exclude=*"

  - name: Install environment dependencies
    dnf:
      name:
        - git
        - pip
      state: latest

  - name: Install pyyaml
    pip:
      name: pyyaml
      state: latest

  - name: Download AI Model
    shell: aws s3 cp {{ s3_bucket }}/boda-ai/ {{ home_dir }}/boda-ai/ --recursive
      
  - name: Install python dependencies
    shell: python3 parse_requirements.py requirements.yaml | xargs /usr/bin/pip install
    args:
      chdir: "{{ home_dir }}/requirements"

  - name: Run BODA
    shell: python3 main.py
    args:
      chdir: "{{ home_dir }}/boda-ai"
    async: 120
    poll: 0