- hosts: backend
  tasks:
  - name: Install environment
    dnf:
      name:
        - docker
        - pip
      state: latest

  - name: Start Docker
    shell: |
      systemctl start docker
      systemctl enable docker

  - name: Install docker-compose
    shell: |
      curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
      chmod +x /usr/local/bin/docker-compose

  - name: Change Docker group
    shell: |
      newgrp docker
      sudo usermod -aG docker $USER
      sudo systemctl restart docker

  - name: Download Server
    shell: aws s3 cp {{ s3_bucket }}/boda-server/docker-compose.yaml .

  - name: Start Docker Compose
    shell: docker-compose up
    async: 120
    poll: 0
    
  # - name: Install environments
  #   dnf:
  #     name:
  #       - git
  #       - java-17-amazon-corretto
  #     state: present

  # - name: Clone backend repository
  #   git:
  #     repo: https://github.com/24Hour-Team/boda-server.git
  #     dest: "{{ home_dir }}/boda-server"
  #     version: develop

  # - name: Change repository permission
  #   file:
  #     path: "{{ home_dir }}/boda-server"
  #     mode: "0755"
  #     recurse: true

  # - name: Build Springboot application
  #   shell: ./gradlew clean build
  #   args:
  #     chdir: "{{ home_dir }}/boda-server"
  #   async: 120
  #   poll: 0
  