- hosts: backend
  become: yes
  tasks:
  - name: Install Git
    dnf:
      name:
        - git
        - java-17-amazon-corretto
      state: present

  - name: Clone backend repo
    git:
      repo: https://github.com/24Hour-Team/boda-server.git
      dest: "{{ home_dir }}/boda-server"
      version: develop

  - name: Build Springboot application
    shell: chmod +x gradlew #&& ./gradlew clean build
    args:
      chdir: "{{ home_dir }}/boda-server"