- hosts: frontend
  become: yes
  tasks:
  - name: Install environments
    dnf:
      name:
        - git
        - npm
      state: latest

  - name: Clone frontend repo
    git:
      repo: https://github.com/24Hour-Team/boda-client.git
      dest: "{{ home_dir }}/boda-client/"
      version: develop

  - name: Install react dependencies
    npm:
      path: "{{ home_dir }}/boda-client"
      state: present

  - name: Run boda-client
    shell: npm start
    args:
      chdir: "{{ home_dir }}/boda-client"
    async: 120
    poll: 0

  - name: React 앱이 실행 중인지 확인
    shell: pgrep -f "node.*react-scripts start"
    register: app_status
    until: app_status.rc == 0
    retries: 10
    delay: 10